# Generated by Django 5.2.12 on 2026-03-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refuge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField()),
                ("capacite_max", models.PositiveIntegerField(default=0)),
                ("zone_hors_eau", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Itineraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
                ("distance", models.FloatField(help_text="Distance en mètres")),
                (
                    "temps_estime",
                    models.PositiveIntegerField(help_text="Temps en secondes"),
                ),
                ("waypoints", models.JSONField(blank=True, default=list)),
                ("fichier_gpx", models.TextField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraires",
                        to="utilisateurs.utilisateur",
                    ),
                ),
                (
                    "refuge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraires",
                        to="evacuation.refuge",
                    ),
                ),
            ],
        ),
    ]
