# Generated by Django 5.2.12 on 2026-03-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("magnitude", models.FloatField()),
                ("epicentre", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("en_mer", models.BooleanField(default=True)),
                (
                    "declenchement",
                    models.CharField(
                        choices=[
                            ("auto", "Automatique"),
                            ("manuel", "Manuel"),
                            ("exercice", "Exercice"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SimulationAlerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("magnitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("epicentre", models.CharField(default="Simulation", max_length=255)),
                ("en_mer", models.BooleanField(default=True)),
                ("traitee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sirene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emplacement", models.CharField(max_length=255)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("inactif", "Inactif")],
                        default="inactif",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
